# Generated by Django 4.0.2 on 2022-07-11 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_productionhouse_movie_production_house'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='tags',
        ),
    ]
